"""Utility modules for JobFinder."""

from src.utils.exceptions import (
    AIQuotaError,
    AIServiceError,
    AITimeoutError,
    ApplyCancelledError,
    ApplyError,
    CaptchaDetectedError,
    ConfigError,
    CVFormatError,
    CVParseError,
    CVScoreError,
    DatabaseConnectionError,
    DatabaseError,
    EmbeddingError,
    FileNotFoundValidationError,
    FormFillError,
    JobFinderError,
    MatchError,
    MissingAPIKeyError,
    ScraperBlockedError,
    ScraperError,
    ScraperTimeoutError,
    ValidationError,
)

__all__ = [
    "AIQuotaError",
    "AIServiceError",
    "AITimeoutError",
    "ApplyCancelledError",
    "ApplyError",
    "CVFormatError",
    "CVParseError",
    "CVScoreError",
    "CaptchaDetectedError",
    "ConfigError",
    "DatabaseConnectionError",
    "DatabaseError",
    "EmbeddingError",
    "FileNotFoundValidationError",
    "FormFillError",
    "JobFinderError",
    "MatchError",
    "MissingAPIKeyError",
    "ScraperBlockedError",
    "ScraperError",
    "ScraperTimeoutError",
    "ValidationError",
]
