"""Export reports for JobFinder — JSON and PDF formats.

Usage:
    from src.utils.exporter import export_results

    # JSON export
    export_results(data, "report.json")

    # PDF export
    export_results(data, "report.pdf", title="CV Analysis Report")
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from config import APP_NAME, APP_VERSION
from src.utils.logging import get_logger

logger = get_logger(__name__)


def export_results(
    data: dict[str, Any], output_path: str | Path, title: str = "JobFinder Report"
) -> str:
    """Export results to JSON or PDF based on file extension.

    Args:
        data: Dictionary containing the data to export.
        output_path: Path to the output file (.json or .pdf).
        title: Report title (used for PDF headers).

    Returns:
        The output path as a string.
    """
    path = Path(output_path)
    ext = path.suffix.lower()

    if ext == ".json":
        return _export_json(data, path)
    elif ext == ".pdf":
        return _export_pdf(data, path, title=title)
    else:
        raise ValueError(f"Unsupported export format: {ext}. Use .json or .pdf")


def _export_json(data: dict[str, Any], path: Path) -> str:
    """Export data as JSON."""
    output = {
        "export_metadata": {
            "tool": APP_NAME,
            "version": APP_VERSION,
            "exported_at": datetime.utcnow().isoformat(),
        },
        **data,
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, default=str, ensure_ascii=False)

    logger.info("Exported JSON report to %s", path)
    return str(path)


def _export_pdf(data: dict[str, Any], path: Path, title: str = "JobFinder Report") -> str:
    """Export data as a PDF report using fpdf2."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 is required for PDF export. Install with: pip install fpdf2")

    path.parent.mkdir(parents=True, exist_ok=True)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title Page ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.ln(40)
    pdf.cell(0, 15, title, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0, 10, f"Generated by {APP_NAME} v{APP_VERSION}", new_x="LMARGIN", new_y="NEXT", align="C"
    )
    pdf.cell(
        0,
        10,
        datetime.utcnow().strftime("%Y-%m-%d %H:%M"),
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )
    pdf.set_text_color(0, 0, 0)

    # ── CV Analysis Section ─────────────────────────────────────────────
    if "parsed" in data or "score" in data:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, "CV Analysis", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Parsed info
        parsed = data.get("parsed", {})
        if parsed:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "Parsed Information", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(
                0,
                6,
                f"  Sections: {', '.join(parsed.get('sections', []))}",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.cell(
                0,
                6,
                f"  Skills: {', '.join(parsed.get('skills', [])[:15])}",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.cell(
                0,
                6,
                f"  Word count: {parsed.get('word_count', 'N/A')}",
                new_x="LMARGIN",
                new_y="NEXT",
            )
            pdf.ln(5)

        # Score
        score = data.get("score", {})
        if score:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "CV Score", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            scores = score.get("scores", {})
            for key, val in scores.items():
                label = key.replace("_", " ").title()
                pdf.cell(0, 6, f"  {label}: {val:.2f}", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(
                0, 6, f"  Overall: {score.get('overall', 0):.2f}", new_x="LMARGIN", new_y="NEXT"
            )
            pdf.ln(5)

            # Suggestions
            suggestions = score.get("suggestions", [])
            if suggestions:
                pdf.set_font("Helvetica", "B", 12)
                pdf.cell(0, 8, "Suggestions", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
                for s in suggestions:
                    pdf.multi_cell(0, 6, f"  - {s}")
                pdf.ln(5)

        # Improvements
        improvements = data.get("improvements", {})
        if improvements:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "AI Improvements", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for change in improvements.get("changes", []):
                pdf.cell(
                    0,
                    6,
                    f"  {change['section']}: {change['original_length']} -> {change['new_length']} chars",
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
            pdf.ln(5)

    # ── Job Matches Section ─────────────────────────────────────────────
    matches = data.get("matches", [])
    if matches:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, f"Job Matches ({len(matches)})", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Table header
        pdf.set_font("Helvetica", "B", 9)
        col_widths = [10, 55, 35, 20, 25, 35]
        headers = ["#", "Title", "Company", "Match", "Source", "Location"]
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 8, header, border=1, align="C")
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        for i, m in enumerate(matches, 1):
            job = m.get("job", {})
            row = [
                str(i),
                job.get("title", "")[:30],
                job.get("company", "")[:20],
                m.get("match_percentage", "N/A"),
                job.get("source", ""),
                job.get("location", "")[:20],
            ]
            for j, val in enumerate(row):
                pdf.cell(col_widths[j], 7, val, border=1, align="C" if j in (0, 3) else "L")
            pdf.ln()

            # Reason on next line
            reason = m.get("reason", "")
            if reason:
                pdf.set_font("Helvetica", "I", 7)
                pdf.multi_cell(0, 5, f"     {reason[:120]}")
                pdf.set_font("Helvetica", "", 8)

    # ── Footer ──────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(
        0, 10, f"Generated by {APP_NAME} v{APP_VERSION}", new_x="LMARGIN", new_y="NEXT", align="C"
    )
    pdf.cell(
        0,
        6,
        datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
        new_x="LMARGIN",
        new_y="NEXT",
        align="C",
    )

    pdf.output(str(path))
    logger.info("Exported PDF report to %s", path)
    return str(path)


def build_analyze_export(parsed: dict, score_data: dict, improvement: dict) -> dict:
    """Build export data structure for the analyze command.

    Args:
        parsed: Parsed CV data from parse_cv().
        score_data: Score data from score_cv().
        improvement: Improvement data from improve_cv().

    Returns:
        Dictionary ready for export_results().
    """
    return {
        "parsed": {
            "sections": list(parsed.get("sections", {}).keys()),
            "skills": parsed.get("skills", []),
            "skill_categories": parsed.get("skill_categories", {}),
            "word_count": parsed.get("word_count", 0),
        },
        "score": {
            "scores": score_data.get("scores", {}),
            "overall": score_data.get("overall", 0),
            "suggestions": score_data.get("suggestions", []),
        },
        "improvements": improvement,
    }


def build_search_export(matches: list[dict], query: str = "", location: str = "") -> dict:
    """Build export data structure for the search command.

    Args:
        matches: List of match results from match_jobs().
        query: The search query used.
        location: The location filter used.

    Returns:
        Dictionary ready for export_results().
    """
    return {
        "search_metadata": {
            "query": query,
            "location": location,
            "total_matches": len(matches),
        },
        "matches": [
            {
                "job": {
                    "title": m["job"].get("title", ""),
                    "company": m["job"].get("company", ""),
                    "url": m["job"].get("url", ""),
                    "source": m["job"].get("source", ""),
                    "location": m["job"].get("location", ""),
                },
                "match_score": m.get("match_score", 0),
                "match_percentage": m.get("match_percentage", ""),
                "reason": m.get("reason", ""),
            }
            for m in matches
        ],
    }
